package de.dafuqs.spectrum.registries;

import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;

public class SpectrumBlockSoundGroups {
	
	// float volume, float pitch, SoundEvent breakSound, SoundEvent stepSound, SoundEvent placeSound, SoundEvent hitSound, SoundEvent fallSound
	public static final BlockSoundGroup CITRINE_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_CITRINE_BLOCK_BREAK, SpectrumSoundEvents.BLOCK_CITRINE_BLOCK_STEP, SpectrumSoundEvents.BLOCK_CITRINE_BLOCK_PLACE, SpectrumSoundEvents.BLOCK_CITRINE_BLOCK_HIT, SpectrumSoundEvents.BLOCK_CITRINE_BLOCK_FALL);
	public static final BlockSoundGroup CITRINE_CLUSTER = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_BREAK, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_PLACE, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_FALL);
	public static final BlockSoundGroup SMALL_CITRINE_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_SMALL_CITRINE_BUD_BREAK, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_SMALL_CITRINE_BUD_PLACE, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_FALL);
	public static final BlockSoundGroup MEDIUM_CITRINE_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_MEDIUM_CITRINE_BUD_BREAK, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_MEDIUM_CITRINE_BUD_PLACE, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_FALL);
	public static final BlockSoundGroup LARGE_CITRINE_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_LARGE_CITRINE_BUD_BREAK, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_LARGE_CITRINE_BUD_PLACE, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_CITRINE_CLUSTER_FALL);
	
	public static final BlockSoundGroup TOPAZ_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_TOPAZ_BLOCK_BREAK, SpectrumSoundEvents.BLOCK_TOPAZ_BLOCK_STEP, SpectrumSoundEvents.BLOCK_TOPAZ_BLOCK_PLACE, SpectrumSoundEvents.BLOCK_TOPAZ_BLOCK_HIT, SpectrumSoundEvents.BLOCK_TOPAZ_BLOCK_FALL);
	public static final BlockSoundGroup TOPAZ_CLUSTER = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_BREAK, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_PLACE, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_FALL);
	public static final BlockSoundGroup SMALL_TOPAZ_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_SMALL_TOPAZ_BUD_BREAK, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_SMALL_TOPAZ_BUD_PLACE, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_FALL);
	public static final BlockSoundGroup MEDIUM_TOPAZ_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_MEDIUM_TOPAZ_BUD_BREAK, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_MEDIUM_TOPAZ_BUD_PLACE, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_FALL);
	public static final BlockSoundGroup LARGE_TOPAZ_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_LARGE_TOPAZ_BUD_BREAK, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_LARGE_TOPAZ_BUD_PLACE, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_TOPAZ_CLUSTER_FALL);
	
	public static final BlockSoundGroup ONYX_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_ONYX_BLOCK_BREAK, SpectrumSoundEvents.BLOCK_ONYX_BLOCK_STEP, SpectrumSoundEvents.BLOCK_ONYX_BLOCK_PLACE, SpectrumSoundEvents.BLOCK_ONYX_BLOCK_HIT, SpectrumSoundEvents.BLOCK_ONYX_BLOCK_FALL);
	public static final BlockSoundGroup ONYX_CLUSTER = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_BREAK, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_PLACE, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_FALL);
	public static final BlockSoundGroup SMALL_ONYX_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_SMALL_ONYX_BUD_BREAK, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_SMALL_ONYX_BUD_PLACE, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_FALL);
	public static final BlockSoundGroup MEDIUM_ONYX_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_MEDIUM_ONYX_BUD_BREAK, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_MEDIUM_ONYX_BUD_PLACE, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_FALL);
	public static final BlockSoundGroup LARGE_ONYX_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_LARGE_ONYX_BUD_BREAK, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_LARGE_ONYX_BUD_PLACE, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_ONYX_CLUSTER_FALL);
	
	public static final BlockSoundGroup MOONSTONE_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_MOONSTONE_BLOCK_BREAK, SpectrumSoundEvents.BLOCK_MOONSTONE_BLOCK_STEP, SpectrumSoundEvents.BLOCK_MOONSTONE_BLOCK_PLACE, SpectrumSoundEvents.BLOCK_MOONSTONE_BLOCK_HIT, SpectrumSoundEvents.BLOCK_MOONSTONE_BLOCK_FALL);
	public static final BlockSoundGroup MOONSTONE_CLUSTER = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_BREAK, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_PLACE, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_FALL);
	public static final BlockSoundGroup SMALL_MOONSTONE_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_SMALL_MOONSTONE_BUD_BREAK, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_SMALL_MOONSTONE_BUD_PLACE, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_FALL);
	public static final BlockSoundGroup MEDIUM_MOONSTONE_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_MEDIUM_MOONSTONE_BUD_BREAK, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_MEDIUM_MOONSTONE_BUD_PLACE, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_FALL);
	public static final BlockSoundGroup LARGE_MOONSTONE_BUD = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.BLOCK_LARGE_MOONSTONE_BUD_BREAK, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_STEP, SpectrumSoundEvents.BLOCK_LARGE_MOONSTONE_BUD_PLACE, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_HIT, SpectrumSoundEvents.BLOCK_MOONSTONE_CLUSTER_FALL);
	
	public static final BlockSoundGroup SPECTRAL_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.SPECTRAL_BLOCK_BREAK, SpectrumSoundEvents.SPECTRAL_BLOCK_STEP, SpectrumSoundEvents.SPECTRAL_BLOCK_PLACE, SpectrumSoundEvents.SPECTRAL_BLOCK_HIT, SpectrumSoundEvents.SPECTRAL_BLOCK_FALL);
	public static final BlockSoundGroup WAND_LIGHT = new BlockSoundGroup(1.0F, 1.0F, SpectrumSoundEvents.RADIANCE_STAFF_BREAK, SoundEvents.BLOCK_AMETHYST_CLUSTER_STEP, SpectrumSoundEvents.RADIANCE_STAFF_PLACE, SpectrumSoundEvents.RADIANCE_STAFF_BREAK, SpectrumSoundEvents.RADIANCE_STAFF_BREAK);
	
	// MOB BLOCKS
	public static final BlockSoundGroup AXOLOTL_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_AXOLOTL_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_AXOLOTL_IDLE_AIR, SoundEvents.ENTITY_AXOLOTL_HURT, SoundEvents.ENTITY_AXOLOTL_IDLE_AIR);
	public static final BlockSoundGroup BAT_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_BAT_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_BAT_AMBIENT, SoundEvents.ENTITY_BAT_HURT, SoundEvents.ENTITY_BAT_AMBIENT);
	public static final BlockSoundGroup BEE_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_BEE_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_BEE_POLLINATE, SoundEvents.ENTITY_BEE_HURT, SoundEvents.ENTITY_BEE_POLLINATE);
	public static final BlockSoundGroup BLAZE_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_BLAZE_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_BLAZE_AMBIENT, SoundEvents.ENTITY_BLAZE_HURT, SoundEvents.ENTITY_BLAZE_AMBIENT);
	public static final BlockSoundGroup CAT_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_CAT_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_CAT_AMBIENT, SoundEvents.ENTITY_CAT_HURT, SoundEvents.ENTITY_CAT_AMBIENT);
	public static final BlockSoundGroup CHICKEN_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_CHICKEN_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_CHICKEN_AMBIENT, SoundEvents.ENTITY_CHICKEN_HURT, SoundEvents.ENTITY_CHICKEN_AMBIENT);
	public static final BlockSoundGroup COW_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_COW_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_COW_AMBIENT, SoundEvents.ENTITY_COW_HURT, SoundEvents.ENTITY_COW_AMBIENT);
	public static final BlockSoundGroup CREEPER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_CREEPER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_CREEPER_HURT, SoundEvents.ENTITY_CREEPER_HURT, SoundEvents.ENTITY_CREEPER_HURT);
	public static final BlockSoundGroup ENDER_DRAGON_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_ENDER_DRAGON_HURT, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_ENDER_DRAGON_AMBIENT, SoundEvents.ENTITY_ENDER_DRAGON_HURT, SoundEvents.ENTITY_ENDER_DRAGON_AMBIENT);
	public static final BlockSoundGroup ENDERMAN_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_ENDERMAN_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_ENDERMAN_AMBIENT, SoundEvents.ENTITY_ENDERMAN_HURT, SoundEvents.ENTITY_ENDERMAN_AMBIENT);
	public static final BlockSoundGroup ENDERMITE_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_ENDERMITE_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_ENDERMITE_AMBIENT, SoundEvents.ENTITY_ENDERMITE_HURT, SoundEvents.ENTITY_ENDERMITE_AMBIENT);
	public static final BlockSoundGroup EVOKER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_EVOKER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_EVOKER_AMBIENT, SoundEvents.ENTITY_EVOKER_HURT, SoundEvents.ENTITY_EVOKER_AMBIENT);
	public static final BlockSoundGroup FISH_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_COD_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_COD_AMBIENT, SoundEvents.ENTITY_COD_HURT, SoundEvents.ENTITY_COD_AMBIENT);
	public static final BlockSoundGroup FOX_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_FOX_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_FOX_AMBIENT, SoundEvents.ENTITY_FOX_HURT, SoundEvents.ENTITY_FOX_AMBIENT);
	public static final BlockSoundGroup GHAST_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_GHAST_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_GHAST_AMBIENT, SoundEvents.ENTITY_GHAST_HURT, SoundEvents.ENTITY_GHAST_AMBIENT);
	public static final BlockSoundGroup GLOW_SQUID_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_GLOW_SQUID_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_GLOW_SQUID_AMBIENT, SoundEvents.ENTITY_GLOW_SQUID_HURT, SoundEvents.ENTITY_GLOW_SQUID_AMBIENT);
	public static final BlockSoundGroup GOAT_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_GOAT_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_GOAT_AMBIENT, SoundEvents.ENTITY_GOAT_HURT, SoundEvents.ENTITY_GOAT_AMBIENT);
	public static final BlockSoundGroup GUARDIAN_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_GUARDIAN_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_GUARDIAN_AMBIENT, SoundEvents.ENTITY_GUARDIAN_HURT, SoundEvents.ENTITY_GUARDIAN_AMBIENT);
	public static final BlockSoundGroup HORSE_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_HORSE_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_HORSE_AMBIENT, SoundEvents.ENTITY_HORSE_HURT, SoundEvents.ENTITY_HORSE_AMBIENT);
	public static final BlockSoundGroup ILLUSIONER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_ILLUSIONER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_ILLUSIONER_AMBIENT, SoundEvents.ENTITY_ILLUSIONER_HURT, SoundEvents.ENTITY_ILLUSIONER_AMBIENT);
	public static final BlockSoundGroup LLAMA_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_LLAMA_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_LLAMA_AMBIENT, SoundEvents.ENTITY_LLAMA_HURT, SoundEvents.ENTITY_LLAMA_AMBIENT);
	public static final BlockSoundGroup OCELOT_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_OCELOT_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_OCELOT_AMBIENT, SoundEvents.ENTITY_OCELOT_HURT, SoundEvents.ENTITY_OCELOT_AMBIENT);
	public static final BlockSoundGroup PARROT_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_PARROT_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_PARROT_AMBIENT, SoundEvents.ENTITY_PARROT_HURT, SoundEvents.ENTITY_PARROT_AMBIENT);
	public static final BlockSoundGroup PHANTOM_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_PHANTOM_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_PHANTOM_AMBIENT, SoundEvents.ENTITY_PHANTOM_HURT, SoundEvents.ENTITY_PHANTOM_AMBIENT);
	public static final BlockSoundGroup PIG_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_PIG_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_PIG_AMBIENT, SoundEvents.ENTITY_PIG_HURT, SoundEvents.ENTITY_PIG_AMBIENT);
	public static final BlockSoundGroup PIGLIN_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_PIGLIN_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_PIGLIN_AMBIENT, SoundEvents.ENTITY_PIGLIN_HURT, SoundEvents.ENTITY_PIGLIN_AMBIENT);
	public static final BlockSoundGroup POLAR_BEAR_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_POLAR_BEAR_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_POLAR_BEAR_AMBIENT, SoundEvents.ENTITY_POLAR_BEAR_HURT, SoundEvents.ENTITY_POLAR_BEAR_AMBIENT);
	public static final BlockSoundGroup PUFFERFISH_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_PUFFER_FISH_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_PUFFER_FISH_AMBIENT, SoundEvents.ENTITY_PUFFER_FISH_HURT, SoundEvents.ENTITY_PUFFER_FISH_AMBIENT);
	public static final BlockSoundGroup RABBIT_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_RABBIT_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_RABBIT_AMBIENT, SoundEvents.ENTITY_RABBIT_HURT, SoundEvents.ENTITY_RABBIT_AMBIENT);
	public static final BlockSoundGroup SHEEP_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SHEEP_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SHEEP_AMBIENT, SoundEvents.ENTITY_SHEEP_HURT, SoundEvents.ENTITY_SHEEP_AMBIENT);
	public static final BlockSoundGroup SHULKER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SHULKER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SHULKER_AMBIENT, SoundEvents.ENTITY_SHULKER_HURT, SoundEvents.ENTITY_SHULKER_AMBIENT);
	public static final BlockSoundGroup SILVERFISH_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SILVERFISH_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SILVERFISH_AMBIENT, SoundEvents.ENTITY_SILVERFISH_HURT, SoundEvents.ENTITY_SILVERFISH_AMBIENT);
	public static final BlockSoundGroup SKELETON_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SKELETON_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SKELETON_AMBIENT, SoundEvents.ENTITY_SKELETON_HURT, SoundEvents.ENTITY_SKELETON_AMBIENT);
	public static final BlockSoundGroup SLIME_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SLIME_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SLIME_SQUISH_SMALL, SoundEvents.ENTITY_SLIME_HURT, SoundEvents.ENTITY_SLIME_SQUISH_SMALL);
	public static final BlockSoundGroup SNOW_GOLEM_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SNOW_GOLEM_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SNOW_GOLEM_AMBIENT, SoundEvents.ENTITY_SNOW_GOLEM_HURT, SoundEvents.ENTITY_SNOW_GOLEM_AMBIENT);
	public static final BlockSoundGroup SPIDER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SPIDER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SPIDER_AMBIENT, SoundEvents.ENTITY_SPIDER_HURT, SoundEvents.ENTITY_SPIDER_AMBIENT);
	public static final BlockSoundGroup SQUID_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_SQUID_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_SQUID_AMBIENT, SoundEvents.ENTITY_SQUID_HURT, SoundEvents.ENTITY_SQUID_AMBIENT);
	public static final BlockSoundGroup STRAY_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_STRAY_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_STRAY_AMBIENT, SoundEvents.ENTITY_STRAY_HURT, SoundEvents.ENTITY_STRAY_AMBIENT);
	public static final BlockSoundGroup STRIDER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_STRIDER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_STRIDER_AMBIENT, SoundEvents.ENTITY_STRIDER_HURT, SoundEvents.ENTITY_STRIDER_AMBIENT);
	public static final BlockSoundGroup TURTLE_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_TURTLE_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_TURTLE_AMBIENT_LAND, SoundEvents.ENTITY_TURTLE_HURT, SoundEvents.ENTITY_TURTLE_AMBIENT_LAND);
	public static final BlockSoundGroup WITCH_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_WITCH_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_WITCH_AMBIENT, SoundEvents.ENTITY_WITCH_HURT, SoundEvents.ENTITY_WITCH_AMBIENT);
	public static final BlockSoundGroup WITHER_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_WITHER_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_WITHER_AMBIENT, SoundEvents.ENTITY_WITHER_HURT, SoundEvents.ENTITY_WITHER_AMBIENT);
	public static final BlockSoundGroup WITHER_SKELETON_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_WITHER_SKELETON_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_WITHER_SKELETON_AMBIENT, SoundEvents.ENTITY_WITHER_SKELETON_HURT, SoundEvents.ENTITY_WITHER_SKELETON_AMBIENT);
	public static final BlockSoundGroup ZOMBIE_MOB_BLOCK = new BlockSoundGroup(1.0F, 1.0F, SoundEvents.ENTITY_ZOMBIE_DEATH, SoundEvents.BLOCK_WOOL_STEP, SoundEvents.ENTITY_ZOMBIE_AMBIENT, SoundEvents.ENTITY_ZOMBIE_HURT, SoundEvents.ENTITY_ZOMBIE_AMBIENT);
	
	public static void register() {
	
	}
	
}
