# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.debug=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neoforge_version=21.1.219
neoforge_version_range=[21.1.186,)

# Mod Properties
mod_id=spectrum
mod_version=1.9.1-neo
maven_group=de.dafuqs
archives_base_name=spectrum

# Dependencies
modmenu_version=11.0.3
rei_version=16.0.799
emi_version=1.1.22+1.21.1
architectury_version=13.0.8
# https://cloudsmith.io/~klikli-dev/repos/mods/groups/
modonomicon_version=1.117.4
modonomicon_version_range=[1.117.4,)
# https://maven.terraformersmc.com/releases/dev/emi/trinkets/
trinkets_version=3.10.0
# https://maven.is-immensely.gay/#/releases/de/dafuqs/additionalentityattributes
additional_entity_attributes_version=2.0.1+1.21.1-neoforge
# https://maven.is-immensely.gay/#/releases/de/dafuqs/revelationary/revelationary
revelationary_version=1.4.0+1.21.1
revelationary_version_range=[1.4.0+1.21.1,)
# https://maven.is-immensely.gay/#/releases/de/dafuqs/fractal
fractal_version=1.7.0+1.21.1-neoforge
# https://maven.is-immensely.gay/#/releases/de/dafuqs/arrowhead
arrowhead_version=2.1.0+1.21.1-neoforge
# https://maven.is-immensely.gay/#/releases/de/dafuqs/reverb
dimensional_reverb_version=1.1.0+1.21.1-neoforge
# https://github.com/Terrails/colorful-heartsf
colorful_hearts_version=us0gze50
# https://modrinth.com/mod/sodium
sodium_version=mc1.21.1-0.6.13-neoforge
# https://modrinth.com/mod/ears
ears_version=1.4.7
# https://modrinth.com/mod/travelersbackpack/
travelers_backpack_version=1.21.1-10.1.31
# https://modrinth.com/mod/botania/
# botania_version=1.20.1-448-fabric
# https://modrinth.com/mod/create-fabric
create_version=mc1.21.1-6.0.9
# https://modrinth.com/mod/malum
malum_version=1.7.3.1
# https://modrinth.com/mod/lodestonelib
lodestone_version=1.20.1-1.6.2.3f
port_lib_version=2.3.8+1.20.1
port_lib_modules=lazy_registration
# https://modrinth.com/mod/exclusions-lib
exclusionslib_version=1.1.0-NEO
# https://modrinth.com/mod/vanity
vanityslots_version=xWfEA0yC
# starry_skies_version=3.2.0+1.21.1

# What recipe viewer to use ('emi', 'rei', or 'disabled')
recipe_viewer=emi
# Datagen runtime mod versions
gobber_version=5736976
ae2_version=eDnBiYjR
# https://modrinth.com/mod/curios/
curios_version=9.5.1+1.21.1
curios_version_range=[9.5.1+1.21.1,)