# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Fabric Properties
minecraft_version=1.21.1
parchment_mappings=1.21.1:2024.11.17
loader_version=0.16.14
# Mod Properties
mod_version=1.9.6
maven_group=de.dafuqs
archives_base_name=spectrum
# Dependencies
# https://fabricmc.net/develop/
fabric_api_version=0.116.4+1.21.1
cloth_config_version=15.0.140
modmenu_version=11.0.3
rei_version=16.0.799
emi_version=1.1.22+1.21.1
architectury_version=13.0.8
# https://cloudsmith.io/~klikli-dev/repos/mods/groups/
modonomicon_version=1.114.5
# https://maven.terraformersmc.com/releases/dev/emi/trinkets/
trinkets_version=3.10.0
cca_version=6.1.2
# https://maven.is-immensely.gay/#/releases/de/dafuqs/additionalentityattributes
additional_entity_attributes_version=2.0.0+1.21.1
# https://maven.is-immensely.gay/#/releases/de/dafuqs/revelationary/revelationary
revelationary_version=1.3.9+1.21.1
# https://maven.is-immensely.gay/#/releases/de/dafuqs/fractal
fractal_version=1.3.0+1.21.1
# https://maven.is-immensely.gay/#/releases/de/dafuqs/arrowhead
arrowhead_version=1.4.4+1.21.1
# https://maven.is-immensely.gay/#/releases/de/dafuqs/reverb
dimensional_reverb_version=1.1.0+1.21.1
# https://github.com/Terrails/colorful-heartsf
colorful_hearts_version=10.3.8
# https://modrinth.com/mod/sodium
sodium_version=mc1.21.1-0.6.13-fabric
# https://github.com/Patbox/common-protection-api
cpa_version=1.0.0
# https://modrinth.com/mod/ears
ears_version=1.4.7
# https://modrinth.com/mod/idwtialsimmoedm/versions
idwtialsimmoedm_version=0.3.2+1.21
# https://modrinth.com/mod/travelersbackpack/
travelers_backpack_version=Mse7s79Y
# https://modrinth.com/mod/botania/
botania_version=1.20.1-448-fabric
# https://modrinth.com/mod/auth-me/
auth_me_version=D0QqKqZn
# https://modrinth.com/mod/create-fabric
create_version=0.5.1-j-build.1631+mc1.20.1
# https://modrinth.com/mod/neepmeat
neepmeat_version=0.13.0-beta+1.20.1
# https://modrinth.com/mod/malum
malum_version=1.20.1-1.6.3.0b-fabric
# https://modrinth.com/mod/lodestonelib
lodestone_version=1.20.1-1.6.2.3f
port_lib_version=2.3.8+1.20.1
port_lib_modules=lazy_registration
# https://modrinth.com/mod/exclusions-lib
exclusionslib_version=R2vQMUlU
# https://modrinth.com/mod/vanity
vanityslots_version=9oyPiBlw

# What recipe viewer to use ('emi', 'rei', or 'disabled')
recipe_viewer=emi
# Datagen runtime mod versions
gobber_version=5736976
ae2_version=eDnBiYjR