$v = @"
minecraft:small_amethyst_bud}[facing=north,waterlogged=true]->2,magenta
minecraft:small_amethyst_bud}[facing=north,waterlogged=false]->2,magenta
minecraft:small_amethyst_bud}[facing=east,waterlogged=true]->2,magenta
minecraft:small_amethyst_bud}[facing=east,waterlogged=false]->2,magenta
minecraft:small_amethyst_bud}[facing=south,waterlogged=true]->2,magenta
minecraft:small_amethyst_bud}[facing=south,waterlogged=false]->2,magenta
minecraft:small_amethyst_bud}[facing=west,waterlogged=true]->2,magenta
minecraft:small_amethyst_bud}[facing=west,waterlogged=false]->2,magenta
minecraft:small_amethyst_bud}[facing=up,waterlogged=true]->2,magenta
minecraft:small_amethyst_bud}[facing=up,waterlogged=false]->2,magenta
minecraft:small_amethyst_bud}[facing=down,waterlogged=true]->2,magenta
minecraft:small_amethyst_bud}[facing=down,waterlogged=false]->2,magenta
minecraft:medium_amethyst_bud}[facing=north,waterlogged=true]->4,magenta
minecraft:medium_amethyst_bud}[facing=north,waterlogged=false]->4,magenta
minecraft:medium_amethyst_bud}[facing=east,waterlogged=true]->4,magenta
minecraft:medium_amethyst_bud}[facing=east,waterlogged=false]->4,magenta
minecraft:medium_amethyst_bud}[facing=south,waterlogged=true]->4,magenta
minecraft:medium_amethyst_bud}[facing=south,waterlogged=false]->4,magenta
minecraft:medium_amethyst_bud}[facing=west,waterlogged=true]->4,magenta
minecraft:medium_amethyst_bud}[facing=west,waterlogged=false]->4,magenta
minecraft:medium_amethyst_bud}[facing=up,waterlogged=true]->4,magenta
minecraft:medium_amethyst_bud}[facing=up,waterlogged=false]->4,magenta
minecraft:medium_amethyst_bud}[facing=down,waterlogged=true]->4,magenta
minecraft:medium_amethyst_bud}[facing=down,waterlogged=false]->4,magenta
minecraft:large_amethyst_bud}[facing=north,waterlogged=true]->6,magenta
minecraft:large_amethyst_bud}[facing=north,waterlogged=false]->6,magenta
minecraft:large_amethyst_bud}[facing=east,waterlogged=true]->6,magenta
minecraft:large_amethyst_bud}[facing=east,waterlogged=false]->6,magenta
minecraft:large_amethyst_bud}[facing=south,waterlogged=true]->6,magenta
minecraft:large_amethyst_bud}[facing=south,waterlogged=false]->6,magenta
minecraft:large_amethyst_bud}[facing=west,waterlogged=true]->6,magenta
minecraft:large_amethyst_bud}[facing=west,waterlogged=false]->6,magenta
minecraft:large_amethyst_bud}[facing=up,waterlogged=true]->6,magenta
minecraft:large_amethyst_bud}[facing=up,waterlogged=false]->6,magenta
minecraft:large_amethyst_bud}[facing=down,waterlogged=true]->6,magenta
minecraft:large_amethyst_bud}[facing=down,waterlogged=false]->6,magenta
minecraft:amethyst_cluster}[facing=north,waterlogged=true]->8,magenta
minecraft:amethyst_cluster}[facing=north,waterlogged=false]->8,magenta
minecraft:amethyst_cluster}[facing=east,waterlogged=true]->8,magenta
minecraft:amethyst_cluster}[facing=east,waterlogged=false]->8,magenta
minecraft:amethyst_cluster}[facing=south,waterlogged=true]->8,magenta
minecraft:amethyst_cluster}[facing=south,waterlogged=false]->8,magenta
minecraft:amethyst_cluster}[facing=west,waterlogged=true]->8,magenta
minecraft:amethyst_cluster}[facing=west,waterlogged=false]->8,magenta
minecraft:amethyst_cluster}[facing=up,waterlogged=true]->8,magenta
minecraft:amethyst_cluster}[facing=up,waterlogged=false]->8,magenta
minecraft:amethyst_cluster}[facing=down,waterlogged=true]->8,magenta
minecraft:amethyst_cluster}[facing=down,waterlogged=false]->8,magenta
spectrum:small_topaz_bud}[facing=north,waterlogged=true]->2,cyan
spectrum:small_topaz_bud}[facing=north,waterlogged=false]->2,cyan
spectrum:small_topaz_bud}[facing=east,waterlogged=true]->2,cyan
spectrum:small_topaz_bud}[facing=east,waterlogged=false]->2,cyan
spectrum:small_topaz_bud}[facing=south,waterlogged=true]->2,cyan
spectrum:small_topaz_bud}[facing=south,waterlogged=false]->2,cyan
spectrum:small_topaz_bud}[facing=west,waterlogged=true]->2,cyan
spectrum:small_topaz_bud}[facing=west,waterlogged=false]->2,cyan
spectrum:small_topaz_bud}[facing=up,waterlogged=true]->2,cyan
spectrum:small_topaz_bud}[facing=up,waterlogged=false]->2,cyan
spectrum:small_topaz_bud}[facing=down,waterlogged=true]->2,cyan
spectrum:small_topaz_bud}[facing=down,waterlogged=false]->2,cyan
spectrum:medium_topaz_bud}[facing=north,waterlogged=true]->4,cyan
spectrum:medium_topaz_bud}[facing=north,waterlogged=false]->4,cyan
spectrum:medium_topaz_bud}[facing=east,waterlogged=true]->4,cyan
spectrum:medium_topaz_bud}[facing=east,waterlogged=false]->4,cyan
spectrum:medium_topaz_bud}[facing=south,waterlogged=true]->4,cyan
spectrum:medium_topaz_bud}[facing=south,waterlogged=false]->4,cyan
spectrum:medium_topaz_bud}[facing=west,waterlogged=true]->4,cyan
spectrum:medium_topaz_bud}[facing=west,waterlogged=false]->4,cyan
spectrum:medium_topaz_bud}[facing=up,waterlogged=true]->4,cyan
spectrum:medium_topaz_bud}[facing=up,waterlogged=false]->4,cyan
spectrum:medium_topaz_bud}[facing=down,waterlogged=true]->4,cyan
spectrum:medium_topaz_bud}[facing=down,waterlogged=false]->4,cyan
spectrum:large_topaz_bud}[facing=north,waterlogged=true]->6,cyan
spectrum:large_topaz_bud}[facing=north,waterlogged=false]->6,cyan
spectrum:large_topaz_bud}[facing=east,waterlogged=true]->6,cyan
spectrum:large_topaz_bud}[facing=east,waterlogged=false]->6,cyan
spectrum:large_topaz_bud}[facing=south,waterlogged=true]->6,cyan
spectrum:large_topaz_bud}[facing=south,waterlogged=false]->6,cyan
spectrum:large_topaz_bud}[facing=west,waterlogged=true]->6,cyan
spectrum:large_topaz_bud}[facing=west,waterlogged=false]->6,cyan
spectrum:large_topaz_bud}[facing=up,waterlogged=true]->6,cyan
spectrum:large_topaz_bud}[facing=up,waterlogged=false]->6,cyan
spectrum:large_topaz_bud}[facing=down,waterlogged=true]->6,cyan
spectrum:large_topaz_bud}[facing=down,waterlogged=false]->6,cyan
spectrum:topaz_cluster}[facing=north,waterlogged=true]->8,cyan
spectrum:topaz_cluster}[facing=north,waterlogged=false]->8,cyan
spectrum:topaz_cluster}[facing=east,waterlogged=true]->8,cyan
spectrum:topaz_cluster}[facing=east,waterlogged=false]->8,cyan
spectrum:topaz_cluster}[facing=south,waterlogged=true]->8,cyan
spectrum:topaz_cluster}[facing=south,waterlogged=false]->8,cyan
spectrum:topaz_cluster}[facing=west,waterlogged=true]->8,cyan
spectrum:topaz_cluster}[facing=west,waterlogged=false]->8,cyan
spectrum:topaz_cluster}[facing=up,waterlogged=true]->8,cyan
spectrum:topaz_cluster}[facing=up,waterlogged=false]->8,cyan
spectrum:topaz_cluster}[facing=down,waterlogged=true]->8,cyan
spectrum:topaz_cluster}[facing=down,waterlogged=false]->8,cyan
spectrum:small_citrine_bud}[facing=north,waterlogged=true]->3,yellow
spectrum:small_citrine_bud}[facing=north,waterlogged=false]->3,yellow
spectrum:small_citrine_bud}[facing=east,waterlogged=true]->3,yellow
spectrum:small_citrine_bud}[facing=east,waterlogged=false]->3,yellow
spectrum:small_citrine_bud}[facing=south,waterlogged=true]->3,yellow
spectrum:small_citrine_bud}[facing=south,waterlogged=false]->3,yellow
spectrum:small_citrine_bud}[facing=west,waterlogged=true]->3,yellow
spectrum:small_citrine_bud}[facing=west,waterlogged=false]->3,yellow
spectrum:small_citrine_bud}[facing=up,waterlogged=true]->3,yellow
spectrum:small_citrine_bud}[facing=up,waterlogged=false]->3,yellow
spectrum:small_citrine_bud}[facing=down,waterlogged=true]->3,yellow
spectrum:small_citrine_bud}[facing=down,waterlogged=false]->3,yellow
spectrum:medium_citrine_bud}[facing=north,waterlogged=true]->5,yellow
spectrum:medium_citrine_bud}[facing=north,waterlogged=false]->5,yellow
spectrum:medium_citrine_bud}[facing=east,waterlogged=true]->5,yellow
spectrum:medium_citrine_bud}[facing=east,waterlogged=false]->5,yellow
spectrum:medium_citrine_bud}[facing=south,waterlogged=true]->5,yellow
spectrum:medium_citrine_bud}[facing=south,waterlogged=false]->5,yellow
spectrum:medium_citrine_bud}[facing=west,waterlogged=true]->5,yellow
spectrum:medium_citrine_bud}[facing=west,waterlogged=false]->5,yellow
spectrum:medium_citrine_bud}[facing=up,waterlogged=true]->5,yellow
spectrum:medium_citrine_bud}[facing=up,waterlogged=false]->5,yellow
spectrum:medium_citrine_bud}[facing=down,waterlogged=true]->5,yellow
spectrum:medium_citrine_bud}[facing=down,waterlogged=false]->5,yellow
spectrum:large_citrine_bud}[facing=north,waterlogged=true]->7,yellow
spectrum:large_citrine_bud}[facing=north,waterlogged=false]->7,yellow
spectrum:large_citrine_bud}[facing=east,waterlogged=true]->7,yellow
spectrum:large_citrine_bud}[facing=east,waterlogged=false]->7,yellow
spectrum:large_citrine_bud}[facing=south,waterlogged=true]->7,yellow
spectrum:large_citrine_bud}[facing=south,waterlogged=false]->7,yellow
spectrum:large_citrine_bud}[facing=west,waterlogged=true]->7,yellow
spectrum:large_citrine_bud}[facing=west,waterlogged=false]->7,yellow
spectrum:large_citrine_bud}[facing=up,waterlogged=true]->7,yellow
spectrum:large_citrine_bud}[facing=up,waterlogged=false]->7,yellow
spectrum:large_citrine_bud}[facing=down,waterlogged=true]->7,yellow
spectrum:large_citrine_bud}[facing=down,waterlogged=false]->7,yellow
spectrum:citrine_cluster}[facing=north,waterlogged=true]->9,yellow
spectrum:citrine_cluster}[facing=north,waterlogged=false]->9,yellow
spectrum:citrine_cluster}[facing=east,waterlogged=true]->9,yellow
spectrum:citrine_cluster}[facing=east,waterlogged=false]->9,yellow
spectrum:citrine_cluster}[facing=south,waterlogged=true]->9,yellow
spectrum:citrine_cluster}[facing=south,waterlogged=false]->9,yellow
spectrum:citrine_cluster}[facing=west,waterlogged=true]->9,yellow
spectrum:citrine_cluster}[facing=west,waterlogged=false]->9,yellow
spectrum:citrine_cluster}[facing=up,waterlogged=true]->9,yellow
spectrum:citrine_cluster}[facing=up,waterlogged=false]->9,yellow
spectrum:citrine_cluster}[facing=down,waterlogged=true]->9,yellow
spectrum:citrine_cluster}[facing=down,waterlogged=false]->9,yellow
spectrum:small_onyx_bud}[facing=north,waterlogged=true]->1,black
spectrum:small_onyx_bud}[facing=north,waterlogged=false]->1,black
spectrum:small_onyx_bud}[facing=east,waterlogged=true]->1,black
spectrum:small_onyx_bud}[facing=east,waterlogged=false]->1,black
spectrum:small_onyx_bud}[facing=south,waterlogged=true]->1,black
spectrum:small_onyx_bud}[facing=south,waterlogged=false]->1,black
spectrum:small_onyx_bud}[facing=west,waterlogged=true]->1,black
spectrum:small_onyx_bud}[facing=west,waterlogged=false]->1,black
spectrum:small_onyx_bud}[facing=up,waterlogged=true]->1,black
spectrum:small_onyx_bud}[facing=up,waterlogged=false]->1,black
spectrum:small_onyx_bud}[facing=down,waterlogged=true]->1,black
spectrum:small_onyx_bud}[facing=down,waterlogged=false]->1,black
spectrum:medium_onyx_bud}[facing=north,waterlogged=true]->3,black
spectrum:medium_onyx_bud}[facing=north,waterlogged=false]->3,black
spectrum:medium_onyx_bud}[facing=east,waterlogged=true]->3,black
spectrum:medium_onyx_bud}[facing=east,waterlogged=false]->3,black
spectrum:medium_onyx_bud}[facing=south,waterlogged=true]->3,black
spectrum:medium_onyx_bud}[facing=south,waterlogged=false]->3,black
spectrum:medium_onyx_bud}[facing=west,waterlogged=true]->3,black
spectrum:medium_onyx_bud}[facing=west,waterlogged=false]->3,black
spectrum:medium_onyx_bud}[facing=up,waterlogged=true]->3,black
spectrum:medium_onyx_bud}[facing=up,waterlogged=false]->3,black
spectrum:medium_onyx_bud}[facing=down,waterlogged=true]->3,black
spectrum:medium_onyx_bud}[facing=down,waterlogged=false]->3,black
spectrum:large_onyx_bud}[facing=north,waterlogged=true]->5,black
spectrum:large_onyx_bud}[facing=north,waterlogged=false]->5,black
spectrum:large_onyx_bud}[facing=east,waterlogged=true]->5,black
spectrum:large_onyx_bud}[facing=east,waterlogged=false]->5,black
spectrum:large_onyx_bud}[facing=south,waterlogged=true]->5,black
spectrum:large_onyx_bud}[facing=south,waterlogged=false]->5,black
spectrum:large_onyx_bud}[facing=west,waterlogged=true]->5,black
spectrum:large_onyx_bud}[facing=west,waterlogged=false]->5,black
spectrum:large_onyx_bud}[facing=up,waterlogged=true]->5,black
spectrum:large_onyx_bud}[facing=up,waterlogged=false]->5,black
spectrum:large_onyx_bud}[facing=down,waterlogged=true]->5,black
spectrum:large_onyx_bud}[facing=down,waterlogged=false]->5,black
spectrum:onyx_cluster}[facing=north,waterlogged=true]->6,black
spectrum:onyx_cluster}[facing=north,waterlogged=false]->6,black
spectrum:onyx_cluster}[facing=east,waterlogged=true]->6,black
spectrum:onyx_cluster}[facing=east,waterlogged=false]->6,black
spectrum:onyx_cluster}[facing=south,waterlogged=true]->6,black
spectrum:onyx_cluster}[facing=south,waterlogged=false]->6,black
spectrum:onyx_cluster}[facing=west,waterlogged=true]->6,black
spectrum:onyx_cluster}[facing=west,waterlogged=false]->6,black
spectrum:onyx_cluster}[facing=up,waterlogged=true]->6,black
spectrum:onyx_cluster}[facing=up,waterlogged=false]->6,black
spectrum:onyx_cluster}[facing=down,waterlogged=true]->6,black
spectrum:onyx_cluster}[facing=down,waterlogged=false]->6,black
spectrum:small_moonstone_bud}[facing=north,waterlogged=true]->6,white
spectrum:small_moonstone_bud}[facing=north,waterlogged=false]->6,white
spectrum:small_moonstone_bud}[facing=east,waterlogged=true]->6,white
spectrum:small_moonstone_bud}[facing=east,waterlogged=false]->6,white
spectrum:small_moonstone_bud}[facing=south,waterlogged=true]->6,white
spectrum:small_moonstone_bud}[facing=south,waterlogged=false]->6,white
spectrum:small_moonstone_bud}[facing=west,waterlogged=true]->6,white
spectrum:small_moonstone_bud}[facing=west,waterlogged=false]->6,white
spectrum:small_moonstone_bud}[facing=up,waterlogged=true]->6,white
spectrum:small_moonstone_bud}[facing=up,waterlogged=false]->6,white
spectrum:small_moonstone_bud}[facing=down,waterlogged=true]->6,white
spectrum:small_moonstone_bud}[facing=down,waterlogged=false]->6,white
spectrum:medium_moonstone_bud}[facing=north,waterlogged=true]->9,white
spectrum:medium_moonstone_bud}[facing=north,waterlogged=false]->9,white
spectrum:medium_moonstone_bud}[facing=east,waterlogged=true]->9,white
spectrum:medium_moonstone_bud}[facing=east,waterlogged=false]->9,white
spectrum:medium_moonstone_bud}[facing=south,waterlogged=true]->9,white
spectrum:medium_moonstone_bud}[facing=south,waterlogged=false]->9,white
spectrum:medium_moonstone_bud}[facing=west,waterlogged=true]->9,white
spectrum:medium_moonstone_bud}[facing=west,waterlogged=false]->9,white
spectrum:medium_moonstone_bud}[facing=up,waterlogged=true]->9,white
spectrum:medium_moonstone_bud}[facing=up,waterlogged=false]->9,white
spectrum:medium_moonstone_bud}[facing=down,waterlogged=true]->9,white
spectrum:medium_moonstone_bud}[facing=down,waterlogged=false]->9,white
spectrum:large_moonstone_bud}[facing=north,waterlogged=true]->12,white
spectrum:large_moonstone_bud}[facing=north,waterlogged=false]->12,white
spectrum:large_moonstone_bud}[facing=east,waterlogged=true]->12,white
spectrum:large_moonstone_bud}[facing=east,waterlogged=false]->12,white
spectrum:large_moonstone_bud}[facing=south,waterlogged=true]->12,white
spectrum:large_moonstone_bud}[facing=south,waterlogged=false]->12,white
spectrum:large_moonstone_bud}[facing=west,waterlogged=true]->12,white
spectrum:large_moonstone_bud}[facing=west,waterlogged=false]->12,white
spectrum:large_moonstone_bud}[facing=up,waterlogged=true]->12,white
spectrum:large_moonstone_bud}[facing=up,waterlogged=false]->12,white
spectrum:large_moonstone_bud}[facing=down,waterlogged=true]->12,white
spectrum:large_moonstone_bud}[facing=down,waterlogged=false]->12,white
spectrum:moonstone_cluster}[facing=north,waterlogged=true]->15,white
spectrum:moonstone_cluster}[facing=north,waterlogged=false]->15,white
spectrum:moonstone_cluster}[facing=east,waterlogged=true]->15,white
spectrum:moonstone_cluster}[facing=east,waterlogged=false]->15,white
spectrum:moonstone_cluster}[facing=south,waterlogged=true]->15,white
spectrum:moonstone_cluster}[facing=south,waterlogged=false]->15,white
spectrum:moonstone_cluster}[facing=west,waterlogged=true]->15,white
spectrum:moonstone_cluster}[facing=west,waterlogged=false]->15,white
spectrum:moonstone_cluster}[facing=up,waterlogged=true]->15,white
spectrum:moonstone_cluster}[facing=up,waterlogged=false]->15,white
spectrum:moonstone_cluster}[facing=down,waterlogged=true]->15,white
spectrum:moonstone_cluster}[facing=down,waterlogged=false]->15,white
spectrum:small_bismuth_bud}[facing=north,waterlogged=true]->4,light_gray
spectrum:small_bismuth_bud}[facing=north,waterlogged=false]->4,light_gray
spectrum:small_bismuth_bud}[facing=east,waterlogged=true]->4,light_gray
spectrum:small_bismuth_bud}[facing=east,waterlogged=false]->4,light_gray
spectrum:small_bismuth_bud}[facing=south,waterlogged=true]->4,light_gray
spectrum:small_bismuth_bud}[facing=south,waterlogged=false]->4,light_gray
spectrum:small_bismuth_bud}[facing=west,waterlogged=true]->4,light_gray
spectrum:small_bismuth_bud}[facing=west,waterlogged=false]->4,light_gray
spectrum:small_bismuth_bud}[facing=up,waterlogged=true]->4,light_gray
spectrum:small_bismuth_bud}[facing=up,waterlogged=false]->4,light_gray
spectrum:small_bismuth_bud}[facing=down,waterlogged=true]->4,light_gray
spectrum:small_bismuth_bud}[facing=down,waterlogged=false]->4,light_gray
spectrum:large_bismuth_bud}[facing=north,waterlogged=true]->6,light_gray
spectrum:large_bismuth_bud}[facing=north,waterlogged=false]->6,light_gray
spectrum:large_bismuth_bud}[facing=east,waterlogged=true]->6,light_gray
spectrum:large_bismuth_bud}[facing=east,waterlogged=false]->6,light_gray
spectrum:large_bismuth_bud}[facing=south,waterlogged=true]->6,light_gray
spectrum:large_bismuth_bud}[facing=south,waterlogged=false]->6,light_gray
spectrum:large_bismuth_bud}[facing=west,waterlogged=true]->6,light_gray
spectrum:large_bismuth_bud}[facing=west,waterlogged=false]->6,light_gray
spectrum:large_bismuth_bud}[facing=up,waterlogged=true]->6,light_gray
spectrum:large_bismuth_bud}[facing=up,waterlogged=false]->6,light_gray
spectrum:large_bismuth_bud}[facing=down,waterlogged=true]->6,light_gray
spectrum:large_bismuth_bud}[facing=down,waterlogged=false]->6,light_gray
spectrum:bismuth_cluster}[facing=north,waterlogged=true]->8,light_gray
spectrum:bismuth_cluster}[facing=north,waterlogged=false]->8,light_gray
spectrum:bismuth_cluster}[facing=east,waterlogged=true]->8,light_gray
spectrum:bismuth_cluster}[facing=east,waterlogged=false]->8,light_gray
spectrum:bismuth_cluster}[facing=south,waterlogged=true]->8,light_gray
spectrum:bismuth_cluster}[facing=south,waterlogged=false]->8,light_gray
spectrum:bismuth_cluster}[facing=west,waterlogged=true]->8,light_gray
spectrum:bismuth_cluster}[facing=west,waterlogged=false]->8,light_gray
spectrum:bismuth_cluster}[facing=up,waterlogged=true]->8,light_gray
spectrum:bismuth_cluster}[facing=up,waterlogged=false]->8,light_gray
spectrum:bismuth_cluster}[facing=down,waterlogged=true]->8,light_gray
spectrum:bismuth_cluster}[facing=down,waterlogged=false]->8,light_gray
spectrum:small_malachite_bud}[facing=north,waterlogged=true]->5,green
spectrum:small_malachite_bud}[facing=north,waterlogged=false]->5,green
spectrum:small_malachite_bud}[facing=east,waterlogged=true]->5,green
spectrum:small_malachite_bud}[facing=east,waterlogged=false]->5,green
spectrum:small_malachite_bud}[facing=south,waterlogged=true]->5,green
spectrum:small_malachite_bud}[facing=south,waterlogged=false]->5,green
spectrum:small_malachite_bud}[facing=west,waterlogged=true]->5,green
spectrum:small_malachite_bud}[facing=west,waterlogged=false]->5,green
spectrum:small_malachite_bud}[facing=up,waterlogged=true]->5,green
spectrum:small_malachite_bud}[facing=up,waterlogged=false]->5,green
spectrum:small_malachite_bud}[facing=down,waterlogged=true]->5,green
spectrum:small_malachite_bud}[facing=down,waterlogged=false]->5,green
spectrum:large_malachite_bud}[facing=north,waterlogged=true]->7,green
spectrum:large_malachite_bud}[facing=north,waterlogged=false]->7,green
spectrum:large_malachite_bud}[facing=east,waterlogged=true]->7,green
spectrum:large_malachite_bud}[facing=east,waterlogged=false]->7,green
spectrum:large_malachite_bud}[facing=south,waterlogged=true]->7,green
spectrum:large_malachite_bud}[facing=south,waterlogged=false]->7,green
spectrum:large_malachite_bud}[facing=west,waterlogged=true]->7,green
spectrum:large_malachite_bud}[facing=west,waterlogged=false]->7,green
spectrum:large_malachite_bud}[facing=up,waterlogged=true]->7,green
spectrum:large_malachite_bud}[facing=up,waterlogged=false]->7,green
spectrum:large_malachite_bud}[facing=down,waterlogged=true]->7,green
spectrum:large_malachite_bud}[facing=down,waterlogged=false]->7,green
spectrum:malachite_cluster}[facing=north,waterlogged=true]->9,green
spectrum:malachite_cluster}[facing=north,waterlogged=false]->9,green
spectrum:malachite_cluster}[facing=east,waterlogged=true]->9,green
spectrum:malachite_cluster}[facing=east,waterlogged=false]->9,green
spectrum:malachite_cluster}[facing=south,waterlogged=true]->9,green
spectrum:malachite_cluster}[facing=south,waterlogged=false]->9,green
spectrum:malachite_cluster}[facing=west,waterlogged=true]->9,green
spectrum:malachite_cluster}[facing=west,waterlogged=false]->9,green
spectrum:malachite_cluster}[facing=up,waterlogged=true]->9,green
spectrum:malachite_cluster}[facing=up,waterlogged=false]->9,green
spectrum:malachite_cluster}[facing=down,waterlogged=true]->9,green
spectrum:malachite_cluster}[facing=down,waterlogged=false]->9,green
spectrum:blackslag_redstone_ore}[lit=true]->9,red
spectrum:azurite_cluster}[facing=north,waterlogged=true]->2,blue
spectrum:azurite_cluster}[facing=north,waterlogged=false]->2,blue
spectrum:azurite_cluster}[facing=east,waterlogged=true]->2,blue
spectrum:azurite_cluster}[facing=east,waterlogged=false]->2,blue
spectrum:azurite_cluster}[facing=south,waterlogged=true]->2,blue
spectrum:azurite_cluster}[facing=south,waterlogged=false]->2,blue
spectrum:azurite_cluster}[facing=west,waterlogged=true]->2,blue
spectrum:azurite_cluster}[facing=west,waterlogged=false]->2,blue
spectrum:azurite_cluster}[facing=up,waterlogged=true]->2,blue
spectrum:azurite_cluster}[facing=up,waterlogged=false]->2,blue
spectrum:azurite_cluster}[facing=down,waterlogged=true]->2,blue
spectrum:azurite_cluster}[facing=down,waterlogged=false]->2,blue
spectrum:large_azurite_bud}[facing=north,waterlogged=true]->3,blue
spectrum:large_azurite_bud}[facing=north,waterlogged=false]->3,blue
spectrum:large_azurite_bud}[facing=east,waterlogged=true]->3,blue
spectrum:large_azurite_bud}[facing=east,waterlogged=false]->3,blue
spectrum:large_azurite_bud}[facing=south,waterlogged=true]->3,blue
spectrum:large_azurite_bud}[facing=south,waterlogged=false]->3,blue
spectrum:large_azurite_bud}[facing=west,waterlogged=true]->3,blue
spectrum:large_azurite_bud}[facing=west,waterlogged=false]->3,blue
spectrum:large_azurite_bud}[facing=up,waterlogged=true]->3,blue
spectrum:large_azurite_bud}[facing=up,waterlogged=false]->3,blue
spectrum:large_azurite_bud}[facing=down,waterlogged=true]->3,blue
spectrum:large_azurite_bud}[facing=down,waterlogged=false]->3,blue
spectrum:small_azurite_bud}[facing=north,waterlogged=true]->5,blue
spectrum:small_azurite_bud}[facing=north,waterlogged=false]->5,blue
spectrum:small_azurite_bud}[facing=east,waterlogged=true]->5,blue
spectrum:small_azurite_bud}[facing=east,waterlogged=false]->5,blue
spectrum:small_azurite_bud}[facing=south,waterlogged=true]->5,blue
spectrum:small_azurite_bud}[facing=south,waterlogged=false]->5,blue
spectrum:small_azurite_bud}[facing=west,waterlogged=true]->5,blue
spectrum:small_azurite_bud}[facing=west,waterlogged=false]->5,blue
spectrum:small_azurite_bud}[facing=up,waterlogged=true]->5,blue
spectrum:small_azurite_bud}[facing=up,waterlogged=false]->5,blue
spectrum:small_azurite_bud}[facing=down,waterlogged=true]->5,blue
spectrum:small_azurite_bud}[facing=down,waterlogged=false]->5,blue
spectrum:small_bloodstone_bud}[facing=north,waterlogged=true]->3,red
spectrum:small_bloodstone_bud}[facing=north,waterlogged=false]->3,red
spectrum:small_bloodstone_bud}[facing=east,waterlogged=true]->3,red
spectrum:small_bloodstone_bud}[facing=east,waterlogged=false]->3,red
spectrum:small_bloodstone_bud}[facing=south,waterlogged=true]->3,red
spectrum:small_bloodstone_bud}[facing=south,waterlogged=false]->3,red
spectrum:small_bloodstone_bud}[facing=west,waterlogged=true]->3,red
spectrum:small_bloodstone_bud}[facing=west,waterlogged=false]->3,red
spectrum:small_bloodstone_bud}[facing=up,waterlogged=true]->3,red
spectrum:small_bloodstone_bud}[facing=up,waterlogged=false]->3,red
spectrum:small_bloodstone_bud}[facing=down,waterlogged=true]->3,red
spectrum:small_bloodstone_bud}[facing=down,waterlogged=false]->3,red
spectrum:large_bloodstone_bud}[facing=north,waterlogged=true]->4,red
spectrum:large_bloodstone_bud}[facing=north,waterlogged=false]->4,red
spectrum:large_bloodstone_bud}[facing=east,waterlogged=true]->4,red
spectrum:large_bloodstone_bud}[facing=east,waterlogged=false]->4,red
spectrum:large_bloodstone_bud}[facing=south,waterlogged=true]->4,red
spectrum:large_bloodstone_bud}[facing=south,waterlogged=false]->4,red
spectrum:large_bloodstone_bud}[facing=west,waterlogged=true]->4,red
spectrum:large_bloodstone_bud}[facing=west,waterlogged=false]->4,red
spectrum:large_bloodstone_bud}[facing=up,waterlogged=true]->4,red
spectrum:large_bloodstone_bud}[facing=up,waterlogged=false]->4,red
spectrum:large_bloodstone_bud}[facing=down,waterlogged=true]->4,red
spectrum:large_bloodstone_bud}[facing=down,waterlogged=false]->4,red
spectrum:bloodstone_cluster}[facing=north,waterlogged=true]->6,red
spectrum:bloodstone_cluster}[facing=north,waterlogged=false]->6,red
spectrum:bloodstone_cluster}[facing=east,waterlogged=true]->6,red
spectrum:bloodstone_cluster}[facing=east,waterlogged=false]->6,red
spectrum:bloodstone_cluster}[facing=south,waterlogged=true]->6,red
spectrum:bloodstone_cluster}[facing=south,waterlogged=false]->6,red
spectrum:bloodstone_cluster}[facing=west,waterlogged=true]->6,red
spectrum:bloodstone_cluster}[facing=west,waterlogged=false]->6,red
spectrum:bloodstone_cluster}[facing=up,waterlogged=true]->6,red
spectrum:bloodstone_cluster}[facing=up,waterlogged=false]->6,red
spectrum:bloodstone_cluster}[facing=down,waterlogged=true]->6,red
spectrum:bloodstone_cluster}[facing=down,waterlogged=false]->6,red
spectrum:shimmerstone_block}->15,shimmerstone
spectrum:topaz_calcite_lamp}->15,cyan
spectrum:amethyst_calcite_lamp}->15,magenta
spectrum:citrine_calcite_lamp}->15,yellow
spectrum:onyx_calcite_lamp}->15,black
spectrum:moonstone_calcite_lamp}->15,white
spectrum:topaz_basalt_lamp}->15,cyan
spectrum:amethyst_basalt_lamp}->15,magenta
spectrum:citrine_basalt_lamp}->15,yellow
spectrum:onyx_basalt_lamp}->15,black
spectrum:moonstone_basalt_lamp}->15,white
spectrum:basalt_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:basalt_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:basalt_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:basalt_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:basalt_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:basalt_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:calcite_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:calcite_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:calcite_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:calcite_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:calcite_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:calcite_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:stone_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:stone_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:stone_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:stone_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:stone_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:stone_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:granite_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:granite_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:granite_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:granite_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:granite_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:granite_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:diorite_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:diorite_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:diorite_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:diorite_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:diorite_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:diorite_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:andesite_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:andesite_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:andesite_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:andesite_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:andesite_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:andesite_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:deepslate_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:deepslate_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:deepslate_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:deepslate_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:deepslate_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:deepslate_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:blackslag_shimmerstone_light}[facing=north]->15,shimmerstone
spectrum:blackslag_shimmerstone_light}[facing=east]->15,shimmerstone
spectrum:blackslag_shimmerstone_light}[facing=south]->15,shimmerstone
spectrum:blackslag_shimmerstone_light}[facing=west]->15,shimmerstone
spectrum:blackslag_shimmerstone_light}[facing=up]->15,shimmerstone
spectrum:blackslag_shimmerstone_light}[facing=down]->15,shimmerstone
spectrum:topaz_chiseled_basalt}->6,cyan
spectrum:amethyst_chiseled_basalt}->5,magenta
spectrum:citrine_chiseled_basalt}->7,yellow
spectrum:onyx_chiseled_basalt}->3,black
spectrum:moonstone_chiseled_basalt}[facing=north]->12,white
spectrum:moonstone_chiseled_basalt}[facing=east]->12,white
spectrum:moonstone_chiseled_basalt}[facing=south]->12,white
spectrum:moonstone_chiseled_basalt}[facing=west]->12,white
spectrum:moonstone_chiseled_basalt}[facing=up]->12,white
spectrum:moonstone_chiseled_basalt}[facing=down]->12,white
spectrum:topaz_chiseled_calcite}->6,cyan
spectrum:amethyst_chiseled_calcite}->5,magenta
spectrum:citrine_chiseled_calcite}->7,yellow
spectrum:onyx_chiseled_calcite}->3,black
spectrum:moonstone_chiseled_calcite}[facing=north]->12,white
spectrum:moonstone_chiseled_calcite}[facing=east]->12,white
spectrum:moonstone_chiseled_calcite}[facing=south]->12,white
spectrum:moonstone_chiseled_calcite}[facing=west]->12,white
spectrum:moonstone_chiseled_calcite}[facing=up]->12,white
spectrum:moonstone_chiseled_calcite}[facing=down]->12,white
spectrum:radiant_glass}->12,shimmerstone
spectrum:radiant_semi_permeable_glass}->12,shimmerstone
spectrum:topaz_chime}->8,cyan
spectrum:amethyst_chime}->5,magenta
spectrum:citrine_chime}->9,yellow
spectrum:onyx_chime}->6,black
spectrum:moonstone_chime}->15,white
spectrum:white_lamp}[lit=true]->15,white
spectrum:orange_lamp}[lit=true]->15,orange
spectrum:magenta_lamp}[lit=true]->15,magenta
spectrum:light_blue_lamp}[lit=true]->15,light_blue
spectrum:yellow_lamp}[lit=true]->15,yellow
spectrum:lime_lamp}[lit=true]->15,lime
spectrum:pink_lamp}[lit=true]->15,pink
spectrum:gray_lamp}[lit=true]->15,gray
spectrum:light_gray_lamp}[lit=true]topa->15,light_gray
spectrum:cyan_lamp}[lit=true]->15,cyan
spectrum:purple_lamp}[lit=true]->15,purple
spectrum:blue_lamp}[lit=true]->15,blue
spectrum:brown_lamp}[lit=true]->15,brown
spectrum:green_lamp}[lit=true]->15,green
spectrum:red_lamp}[lit=true]->15,red
spectrum:black_lamp}[lit=true]->15,black
spectrum:white_glowblock}->1,white
spectrum:orange_glowblock}->1,orange
spectrum:magenta_glowblock}->1,magenta
spectrum:light_blue_glowblock}->1,light_blue
spectrum:yellow_glowblock}->1,yellow
spectrum:lime_glowblock}->1,lime
spectrum:pink_glowblock}->1,pink
spectrum:gray_glowblock}->1,gray
spectrum:light_gray_glowblock}->1,light_gray
spectrum:cyan_glowblock}->1,cyan
spectrum:purple_glowblock}->1,purple
spectrum:blue_glowblock}->1,blue
spectrum:brown_glowblock}->1,brown
spectrum:green_glowblock}->1,green
spectrum:red_glowblock}->1,red
spectrum:black_glowblock}->1,black
spectrum:slate_noxcap_gills}[axis=x]->12,slate_noxwood
spectrum:slate_noxcap_gills}[axis=y]->12,slate_noxwood
spectrum:slate_noxcap_gills}[axis=z]->12,slate_noxwood
spectrum:slate_noxwood_lantern}[lit=true]->15,slate_noxwood
spectrum:slate_noxwood_light}[axis=x]->15,slate_noxwood
spectrum:slate_noxwood_light}[axis=y]->15,slate_noxwood
spectrum:slate_noxwood_light}[axis=z]->15,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=false]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=true]->13,slate_noxwood
spectrum:slate_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=false]->13,slate_noxwood
spectrum:ebony_noxcap_gills}[axis=x]->12,ebony_noxwood
spectrum:ebony_noxcap_gills}[axis=y]->12,ebony_noxwood
spectrum:ebony_noxcap_gills}[axis=z]->12,ebony_noxwood
spectrum:ebony_noxwood_lantern}[lit=true]->15,ebony_noxwood
spectrum:ebony_noxwood_light}[axis=x]->15,ebony_noxwood
spectrum:ebony_noxwood_light}[axis=y]->15,ebony_noxwood
spectrum:ebony_noxwood_light}[axis=z]->15,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=false]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=true]->13,ebony_noxwood
spectrum:ebony_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=false]->13,ebony_noxwood
spectrum:ivory_noxcap_gills}[axis=x]->12,ivory_noxwood
spectrum:ivory_noxcap_gills}[axis=y]->12,ivory_noxwood
spectrum:ivory_noxcap_gills}[axis=z]->12,ivory_noxwood
spectrum:ivory_noxwood_lantern}[lit=true]->15,ivory_noxwood
spectrum:ivory_noxwood_light}[axis=x]->15,ivory_noxwood
spectrum:ivory_noxwood_light}[axis=y]->15,ivory_noxwood
spectrum:ivory_noxwood_light}[axis=z]->15,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=false]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=true]->13,ivory_noxwood
spectrum:ivory_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=false]->13,ivory_noxwood
spectrum:chestnut_noxcap_gills}[axis=x]->12,chestnut_noxwood
spectrum:chestnut_noxcap_gills}[axis=y]->12,chestnut_noxwood
spectrum:chestnut_noxcap_gills}[axis=z]->12,chestnut_noxwood
spectrum:chestnut_noxwood_lantern}[lit=true]->15,chestnut_noxwood
spectrum:chestnut_noxwood_light}[axis=x]->15,chestnut_noxwood
spectrum:chestnut_noxwood_light}[axis=y]->15,chestnut_noxwood
spectrum:chestnut_noxwood_light}[axis=z]->15,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=true,hanging=true,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=true,hanging=false,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=false,hanging=true,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=true,diagonal=false,hanging=false,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=true,hanging=true,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=true,hanging=false,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=false,hanging=true,waterlogged=false]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=true]->13,chestnut_noxwood
spectrum:chestnut_noxwood_lamp}[alt=false,diagonal=false,hanging=false,waterlogged=false]->13,chestnut_noxwood
spectrum:hummingstone}[humming=true]->14,light_blue
spectrum:hummingstone}[humming=false]->14,light_blue
spectrum:wet_lava_sponge}->9,orange
spectrum:sugar_stick}[age=0,fluid_logged=none]->15,light_gray
spectrum:sugar_stick}[age=0,fluid_logged=liquid_crystal]->15,light_gray
spectrum:sugar_stick}[age=1,fluid_logged=none]->15,light_gray
spectrum:sugar_stick}[age=1,fluid_logged=liquid_crystal]->15,light_gray
spectrum:sugar_stick}[age=2,fluid_logged=none]->15,light_gray
spectrum:sugar_stick}[age=2,fluid_logged=liquid_crystal]->17,light_gray
spectrum:topaz_sugar_stick}[age=0,fluid_logged=none]->15,cyan
spectrum:topaz_sugar_stick}[age=0,fluid_logged=liquid_crystal]->15,cyan
spectrum:topaz_sugar_stick}[age=1,fluid_logged=none]->15,cyan
spectrum:topaz_sugar_stick}[age=1,fluid_logged=liquid_crystal]->15,cyan
spectrum:topaz_sugar_stick}[age=2,fluid_logged=none]->15,cyan
spectrum:topaz_sugar_stick}[age=2,fluid_logged=liquid_crystal]->17,cyan
spectrum:amethyst_sugar_stick}[age=0,fluid_logged=none]->15,magenta
spectrum:amethyst_sugar_stick}[age=0,fluid_logged=liquid_crystal]->15,magenta
spectrum:amethyst_sugar_stick}[age=1,fluid_logged=none]->15,magenta
spectrum:amethyst_sugar_stick}[age=1,fluid_logged=liquid_crystal]->15,magenta
spectrum:amethyst_sugar_stick}[age=2,fluid_logged=none]->15,magenta
spectrum:amethyst_sugar_stick}[age=2,fluid_logged=liquid_crystal]->17,magenta
spectrum:citrine_sugar_stick}[age=0,fluid_logged=none]->15,yellow
spectrum:citrine_sugar_stick}[age=0,fluid_logged=liquid_crystal]->15,yellow
spectrum:citrine_sugar_stick}[age=1,fluid_logged=none]->15,yellow
spectrum:citrine_sugar_stick}[age=1,fluid_logged=liquid_crystal]->15,yellow
spectrum:citrine_sugar_stick}[age=2,fluid_logged=none]->15,yellow
spectrum:citrine_sugar_stick}[age=2,fluid_logged=liquid_crystal]->17,yellow
spectrum:onyx_sugar_stick}[age=0,fluid_logged=none]->15,black
spectrum:onyx_sugar_stick}[age=0,fluid_logged=liquid_crystal]->15,black
spectrum:onyx_sugar_stick}[age=1,fluid_logged=none]->15,black
spectrum:onyx_sugar_stick}[age=1,fluid_logged=liquid_crystal]->15,black
spectrum:onyx_sugar_stick}[age=2,fluid_logged=none]->15,black
spectrum:onyx_sugar_stick}[age=2,fluid_logged=liquid_crystal]->17,black
spectrum:moonstone_sugar_stick}[age=0,fluid_logged=none]->15,white
spectrum:moonstone_sugar_stick}[age=0,fluid_logged=liquid_crystal]->15,white
spectrum:moonstone_sugar_stick}[age=1,fluid_logged=none]->15,white
spectrum:moonstone_sugar_stick}[age=1,fluid_logged=liquid_crystal]->15,white
spectrum:moonstone_sugar_stick}[age=2,fluid_logged=none]->15,white
spectrum:moonstone_sugar_stick}[age=2,fluid_logged=liquid_crystal]->17,white
spectrum:shimmering_preservation_bricks}->5,blue
spectrum:powder_chiseled_preservation_stone}->2,blue
spectrum:dike_chiseled_preservation_stone}->6,blue
spectrum:tinted_preservation_glass}->12,cyan
spectrum:dike_gate}->3,blue
spectrum:preservation_controller}[facing=north]->1,cyan
spectrum:preservation_controller}[facing=south]->1,cyan
spectrum:preservation_controller}[facing=west]->1,cyan
spectrum:preservation_controller}[facing=east]->1,cyan
spectrum:frostbite_crystal}->15,light_blue
spectrum:blazing_crystal}->15,orange
"@

$w = $v -split "`r`n"
$w | Foreach-Object {
    $_ = $_.replace("}", "")
    $_ = $_.replace("\]", "")
    $_ = $_.replace("-", "")

    $other, $brightness_color = $_ -split ">"
    $brightness, $color = $brightness_color -split ","
    $block, $stateList = $other -split "\["
    $states = @{}
    if($stateList) {

@"
{
  "block": "$block",
  "state": {
"@
        $stateList = $stateList.replace("]", "")
        $i = 0
        if($block -match "onyx_sugar_stick") {
            Write-Host "!"
        }

        $entries = $stateList -split ","
        $entryCount = $entries.Count
        for($i = 0; $i -lt $entryCount; $i++) {
            $entry = $entries[$i]
            $comma = If($i -eq $entryCount -1) {""} else {","}
            $k, $v = $entry -split "="
            if($v -match '^[0-9.]+$' -or $v -match "true" -or $v -match "false") {
                "    `"$k`": $v$comma"
            } else {
                "    `"$k`": `"$v`"$comma"
            }
        }
@"
  },
  "color": "#$color",
  "radius": $brightness
},
"@
    } else {
@"
{
  "block": "$block",
  "color": "#$color",
  "radius": $brightness
},
"@
    }
}

