package de.dafuqs.spectrum.entity.animation;

import net.minecraft.client.animation.*;

public class KindlingAnimations {
	
	// EntityPose.SNIFFING
	public static final AnimationDefinition WALKING = AnimationDefinition.Builder.withLength(0.8343334f).looping()
			.addAnimation("torso",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0.38f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.posVec(-0.37f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.posVec(0.38f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 142.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 147.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 142.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, 147.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 142.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -142.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, -147.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -142.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, -147.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, -142.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightbackleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftbackleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("midtail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fartail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -5f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 5f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, -5f, -5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -5f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 5f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, -5f, 5f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	// EntityPose.EMERGING
	public static final AnimationDefinition WALKING_ANGRY = AnimationDefinition.Builder.withLength(0.8343334f).looping()
			.addAnimation("torso",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0.38f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -1.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.posVec(-0.37f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.posVec(0f, -1.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.posVec(0.38f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 32.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 32.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 32.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightbackleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftbackleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("midtail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fartail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-1.51f, -4.77f, 12.56f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(1.08f, 4.88f, 7.55f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-1.51f, -4.77f, 12.56f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-1.51f, -4.77f, -12.56f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(1.08f, 4.88f, -7.55f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-1.51f, -4.77f, -12.56f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	// EntityPose.STANDING
	public static final AnimationDefinition STANDING = AnimationDefinition.Builder.withLength(3.4167665f).looping()
			.addAnimation("rightwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(4.98f, -0.44f, 4.98f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 142.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 140f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 0f, 142.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(4.98f, 0.44f, -4.98f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -142.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, -140f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 0f, -142.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("midtail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fartail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	// EntityPose.ROARING
	public static final AnimationDefinition STANDING_ANGRY = AnimationDefinition.Builder.withLength(3.4167665f).looping()
			.addAnimation("rightwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(4.83f, -1.29f, 14.95f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(4.62f, -1.91f, 22.42f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(4.83f, -1.29f, 14.95f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(4.83f, -1.29f, -14.95f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(4.62f, -1.91f, -22.42f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(4.83f, -1.29f, -14.95f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("midtail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fartail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(-0.5f, -1f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.3433335f, KeyframeAnimations.posVec(0.5f, -1f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.2083435f, KeyframeAnimations.posVec(0f, 0f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.posVec(-0.5f, -1f, -1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightforeleg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.posVec(0f, 1f, -0.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.posVec(0f, 0f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.9583435f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftforeleg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 1f, -0.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	// EntityPose.FALL_FLYING
	public static final AnimationDefinition GLIDING = AnimationDefinition.Builder.withLength(4f).looping()
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -2.5f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.posVec(0f, -2.5f, -1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 57.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 60f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 57.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftwing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -57.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -60f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, -57.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wingjoint2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(57.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(62.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(57.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftforeleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(57.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(62.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(57.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightbackleg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightbackleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(62.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftbackleg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftbackleg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(62.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 4f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("midtail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fartail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	
}
