# TODO: remove modLoader and loaderVersion in 1.21.6+
modLoader="javafml"
loaderVersion="[1,)"
license="lGPL3"
issueTrackerURL="https://github.com/DaFuqs/Spectrum/issues"

[[mods]]
modId="spectrum"
version="${version}"
displayName="Spectrum"
displayURL="https://github.com/DaFuqs/Spectrum"
logoFile="assets/spectrum/icon.png"
authors="DaFuqs, Azzyypaaras, Noaaan, Electro_593"
description='''A full-feature magic mod about harnessing the powers of color'''

[[mixins]]
config="spectrum.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.spectrum]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.spectrum]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.spectrum]]
modId="revelationary"
type="required"
versionRange="${revelationary_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.spectrum]]
modId="modonomicon"
type="required"
versionRange="${modonomicon_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.spectrum]]
modId="curios"
type="required"
versionRange="${curios_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.spectrum]]
modId="malum"
type="optional"
reason="load after malum to fix https://github.com/SammySemicolon/Malum-Mod/issues/445"
versionRange="[1.8.2,)"
ordering="AFTER"
side="BOTH"