# Builds the project with every commit to confirm that the mod works.

# Based on fabric-example-mod's workflow, with more comments.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [17] # Current Java LTS & minimum supported by Minecraft
        # Test on both Linux and Windows
        os: [ubuntu-20.04, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: make gradle wrapper executable
        # Linux requires that files are marked executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      
      - name: build
        run: ./gradlew build
      
      - name: capture build artifacts
        # Only capture artifacts from one OS (Linux)
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/


